apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ocifit-test
  region: us-east-2
  version: "1.32"

availabilityZones: ["us-east-2b", "us-east-2c"]
managedNodeGroups:
  - name: workers
    availabilityZones: ["us-east-2b"]
    instanceType: hpc6a.48xlarge
    volumeSize: 150
    volumeType: gp2
    minSize: 1
    maxSize: 1
    efaEnabled: true
    placement:
      groupName: performance-study
