apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: nfd-cluster
  region: us-east-1

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]
managedNodeGroups:
  - name: ng-c7a-large
    availabilityZones: ["us-east-1b"]
    instanceType: c7a.12xlarge
    volumeSize: 20
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 1

  - name: ng-hpc7g-16xlarge
    availabilityZones: ["us-east-1a"]
    instanceType: hpc7g.16xlarge
    volumeSize: 20
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 1

  - name: ng-c6in-4xlarge
    availabilityZones: ["us-east-1b"]
    instanceType: c6in.12xlarge
    volumeSize: 20
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 1

  - name: ng-r7iz-large
    availabilityZones: ["us-east-1b"]
    instanceType: r7iz.8xlarge
    volumeSize: 20
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 1

  - name: ng-m6g-large
    availabilityZones: ["us-east-1b"]
    instanceType: m6g.12xlarge
    volumeSize: 20
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 1
      
  - name: ng-t3a-medium
    instanceType: t3a.2xlarge
    volumeSize: 20
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 1

  - name: ng-t3-medium
    instanceType: t3.2xlarge
    volumeSize: 20
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 1

  # Intel General Purpose with Local NVMe
  - name: ng-m6id-large
    instanceType: m6id.12xlarge
    volumeSize: 20
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 1

  # Intel Compute Optimized with Local NVMe
  - name: ng-c6id-large
    instanceType: c6id.12xlarge
    volumeSize: 20
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 1

  # AWS Inferentia2 - ML Inference
  # ARM-based, purpose-built for deep learning inference. Adds a specialized ML instance.
  # Requires specific Neuron SDK and compiled models.
  - name: ng-inf2-xlarge
    instanceType: inf2.xlarge
    volumeSize: 20
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 1

  # ARM
  - name: ng-t4g-medium
    instanceType: t4g.2xlarge
    volumeSize: 20
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 1

  # --- General Purpose - Standard ---
  - name: ng-m6i-large
    instanceType: m6i.12xlarge
    volumeSize: 30
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 1

  - name: ng-m6a-large
    instanceType: m6a.12xlarge
    volumeSize: 30
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 1

   # ARM instance
  - name: ng-m7g-large
    instanceType: m7g.16xlarge
    volumeSize: 30
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 1

    # --- Compute Optimized ---
  - name: ng-c6i-large
    instanceType: c6i.large
    volumeSize: 30
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 1

  - name: ng-c6a-large
    instanceType: c6a.16.xlarge
    volumeSize: 30
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 1

   # ARM instance
  - name: ng-c7g-large
    instanceType: c7g.16xlarge
    volumeSize: 30
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 1

  # --- Memory Optimized ---
  - name: ng-r6i-large
    instanceType: r6i.8xlarge
    amiFamily: AmazonLinux2
    volumeSize: 30
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 1

  - name: ng-r6a-large
    instanceType: r6a.12xlarge
    volumeSize: 30
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 1

  - name: ng-r7g-large
    instanceType: r7g.12xlarge
    volumeSize: 30
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 1

  # --- Storage Optimized ---
  - name: ng-i4i-large
    instanceType: i4i.8xlarge
    volumeSize: 30 # Root volume, actual NVMe is instance store
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 1

  # --- Dense Storage (HDD) ---
  - name: ng-d3-xlarge
    instanceType: d3.4xlarge
    volumeSize: 30
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 1

